# Generated by Django 2.1.7 on 2019-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191015_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspot',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
