# Generated by Django 2.1.7 on 2019-09-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
