# Generated by Django 2.1.7 on 2019-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20191011_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(max_length=50)),
                ('q_email', models.CharField(max_length=50)),
                ('q_phone', models.CharField(max_length=10)),
                ('q_query', models.CharField(max_length=200)),
            ],
        ),
    ]
