# Generated by Django 2.1.7 on 2019-10-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_query'),
    ]

    operations = [
        migrations.DeleteModel(
            name='query',
        ),
    ]
