# Generated by Django 2.1.7 on 2019-10-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20191014_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderUpdate',
            new_name='Update',
        ),
    ]
