# Generated by Django 2.1.7 on 2019-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20191014_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
